export default [
  {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987108/drizzle/rainnight_tm7zsb.png',
    desc: 'city street after rain',
    author: 'u/ruetanissed',
    authorLink: 'https://www.reddit.com/user/ruetanissed',
    time: ['night'],
    types: ['Rain'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987141/drizzle/maxresdefault_ikqxbh.jpg',
    desc: 'girl with a guitar',
    author: 'Dreamy',
    authorLink: 'https://www.instagram.com/its_dreamy_yt/',
    time: ['day', 'sunset', 'sunrise'],
    types: ['Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987169/drizzle/create-lofi-hip-hop-animations_qbwaqb.jpg',
    desc: 'girl on couch reading book',
    author: 'sandrotsk',
    authorLink: 'https://www.fiverr.com/sandrotsk',
    time: ['night'],
    types: ['Clear', 'Few Clouds', 'Clouds', 'Mist', 'Rain', 'Drizzle'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987196/drizzle/create-lofi-hip-hop-animations_qz8ukq.jpg',
    desc: 'guy playing video games on couch',
    author: 'sandrotsk',
    authorLink: 'https://www.fiverr.com/sandrotsk',
    time: ['night'],
    types: ['Rain', 'Drizzle', 'Thunderstorm'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987203/drizzle/create-lofi-hip-hop-animations_kyn5q2.jpg',
    desc: 'girl studying next to window',
    author: 'sandrotsk',
    authorLink: 'https://www.fiverr.com/sandrotsk',
    time: ['day', 'sunset'],
    types: ['Rain', 'Drizzle'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987585/drizzle/33401_ykte4o.jpg',
    desc: 'pond with lily pads',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['night', 'sunset', 'sunrise'],
    types: ['Clear', 'Few Clouds', 'Mist'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987591/drizzle/543608_asstv6.jpg',
    desc: 'asian street',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987597/drizzle/642945_br88rk.jpg',
    desc: 'raccoon on bed',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['night'],
    types: ['Clear', 'Few Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987603/drizzle/647764_j3okci.jpg',
    desc: 'girl on floor looking outsite',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['sunrise', 'sunset'],
    types: ['Clear', 'Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987609/drizzle/647904_rsyx8d.jpg',
    desc: 'asian street during the day',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['day'],
    types: ['Clear', 'Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987615/drizzle/866271_o3xczy.jpg',
    desc: 'girl looking at tree',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['sunset', 'sunrise'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987621/drizzle/937699_lql9j6.jpg',
    desc: 'boy under a tree',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['day'],
    types: ['Clear', 'Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987628/drizzle/1584344_fuzxjn.png',
    desc: 'empty stree with trees',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['day'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987633/drizzle/1991420_doggp4.jpg',
    desc: 'girl looking at mountains and clouds',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['day'],
    types: ['Few Clouds', 'Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987639/drizzle/1991430_p4p8q1.jpg',
    desc: 'open field during sunset or sunrise',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['sunset', 'sunrise'],
    types: ['Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602987645/drizzle/1991469_c2i8bl.jpg',
    desc: 'empty swing on a tree',
    author: 'WallpaperAccess',
    authorLink: 'https://wallpaperaccess.com/',
    time: ['day'],
    types: ['Clear', 'Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988268/drizzle/lorenzo-lanfranconi-ex-22-f_z1te5b.jpg',
    desc: 'animals on mountain',
    author: 'Lorenzo Lanfranconi',
    authorLink: 'https://www.artstation.com/lorenzolanfranconi',
    time: ['day'],
    types: ['Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988300/drizzle/syna-z-6-16_qn9gh8.jpg',
    desc: 'street in front of movie theatre',
    author: 'Syna Z',
    authorLink: 'https://www.artstation.com/synaz',
    time: ['sunset'],
    types: ['Few Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988324/drizzle/henrik-evensen-winter-forest_dyb1es.jpg',
    desc: 'snowy forest',
    author: 'Henrik Evensen',
    authorLink: 'https://www.artstation.com/selvestehe',
    time: ['sunrise', 'day'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988357/drizzle/henrik-evensen-rocky-rox-04_kkiuyj.jpg',
    desc: 'snowy rocky path',
    author: 'Henrik Evensen',
    authorLink: 'https://www.artstation.com/selvestehe',
    time: ['day'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988387/drizzle/slawek-fedorczuk-slawek-fedorczuk-2016-11-23_g7ugu1.jpg',
    desc: 'snowy cottages',
    author: 'Slawek Fedorczuk',
    authorLink: 'https://www.artstation.com/slawekfedorczuk',
    time: ['day'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988432/drizzle/atey-ghailan-125_fdzgbw.jpg',
    desc: 'two girls in the rain',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['night'],
    types: ['Rain', 'Thunderstorm', 'Drizzle'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988445/drizzle/atey-ghailan-1_fvpeqr.jpg',
    desc: 'girl walking dog in snow',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['sunrise', 'sunset'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988495/drizzle/atey-ghailan-final-painting_cfslfz.jpg',
    desc: 'girl fishing at night',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988522/drizzle/atey-ghailan-garden-words-final_llnfjm.jpg',
    desc: 'girl sitting in the rain',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['day', 'sunset', 'sunrise'],
    types: ['Rain', 'Thunderstorm', 'Drizzle'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988559/drizzle/atey-ghailan-161_znm9u7.jpg',
    desc: 'girl waiting for a bus',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['sunset', 'sunrise'],
    types: ['Few Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988582/drizzle/atey-ghailan-243_zlx5ws.jpg',
    desc: 'boy standing on flooded railroad track',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['sunset', 'sunrise'],
    types: ['Clouds', 'Few Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602988612/drizzle/atey-ghailan-241_h6wdte.jpg',
    desc: 'girl sitting on a hill',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['day', 'sunset'],
    types: ['Clouds', 'Mist'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989320/drizzle/bogdan-martynenko-semaphorefinalhd_ekxuhi.jpg',
    desc: 'open field with a railroad sign',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['day'],
    types: ['Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989339/drizzle/bogdan-mb0sco-busstopeven-previewbus_i5rm3f.jpg',
    desc: 'bus stop during the day',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['day', 'sunset', 'sunrise'],
    types: ['Few Clouds', 'Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989358/drizzle/bogdan-mb0sco-busstopnight-previewtrolleybus_xwexeg.jpg',
    desc: 'bus stop at night',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night', 'sunset', 'sunrise'],
    types: ['Few Clouds', 'Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989377/drizzle/bogdan-mb0sco-cafe-day-sign-web_v33sx5.jpg',
    desc: 'empty storefront',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['day'],
    types: ['Few Clouds', 'Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989396/drizzle/bogdan-mb0sco-citylights-prewievf-3840_p95ein.jpg',
    desc: 'view of city from a balcony',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Few Clouds', 'Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989415/drizzle/bogdan-mb0sco-coffee-shop-hdpreview_skdhpw.jpg',
    desc: 'front of coffee shop',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989434/drizzle/bogdan-mb0sco-coffee-shop-snow-hdpreview_kvsgex.jpg',
    desc: 'front of coffee shop with snow',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Snow'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989453/drizzle/bogdan-mb0sco-donnuts-hd2_bsnnmc.jpg',
    desc: 'front of donut shop',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989472/drizzle/bogdan-mb0sco-gas-station-static-web_plhfpj.jpg',
    desc: 'gas station at night',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Clear', 'Mist'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989491/drizzle/bogdan-mb0sco-japanstreet-previewweb_j97yy3.jpg',
    desc: 'traditional japanese street',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['sunrise', 'day'],
    types: ['Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989511/drizzle/bogdan-mb0sco-jazzhopcafe-arts1_fhvwa7.jpg',
    desc: 'empty bar',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['sunset', 'night'],
    types: ['Clear', 'Few Clouds', 'Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989530/drizzle/bogdan-mb0sco-roomwebpreview_hlp12w.jpg',
    desc: 'sunny room',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['day'],
    types: ['Few Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989549/drizzle/bogdan-mb0sco-school-entry-day-sign_qgjcer.jpg',
    desc: 'empty school',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['day'],
    types: ['Clouds', 'Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989568/drizzle/bogdan-mb0sco-school-nighthd_wau2an.jpg',
    desc: 'empty school at night',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602989587/drizzle/bogdan-mb0sco-vs-previewhd_mwcbgk.jpg',
    desc: 'storefront at night',
    author: 'Bogdan mB0sco',
    authorLink: 'https://www.artstation.com/mb0sco',
    time: ['night'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602990731/drizzle/atey-ghailan-final_t8snfh.jpg',
    desc: 'girl walking on bridge',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['night'],
    types: ['Clouds'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602991178/drizzle/atey-ghailan-final-painting_qftktv.jpg',
    desc: 'girl on bike watching sunset',
    author: 'Atey Ghailan',
    authorLink: 'https://www.artstation.com/snatti',
    time: ['sunset', 'sunrise'],
    types: ['Clear'],
  }, {
    link: 'https://res.cloudinary.com/dhzssvuhz/image/upload/v1602992687/drizzle/wallpaper_mikael_gustafsson_ucccf1.webp',
    desc: 'river sunset or sunrise',
    author: 'Mikael Gustafsson',
    authorLink: 'https://twitter.com/mklgustafsson?lang=en',
    time: ['sunset', 'sunrise'],
    types: ['Clear', 'Mist'],
  },
];
